#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 08:00:00
#SBATCH -J BWA_for_RNA_after_metabat_1_2
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

set -x

#Load modules
module load bioinfo-tools
module load bwa
module load samtools

#directories used
seqdir1="/proj/genomeanalysis2022/nobackup/work/kvenk811/Metabat_binning_before_bwa"
#seqdir2="/proj/genomeanalysis2022/nobackup/work/kvenk811/metabat_after_bwa"
outdir="/proj/genomeanalysis2022/nobackup/work/kvenk811/bwa_conc_rna_map"
source="/proj/genomeanalysis2022/nobackup/work/kvenk811//RNA_trimmed_files"


#run bwa for each bin
# Align RNA reads to each fasta file, and convert to a sorted bam format.
# Also produce some index stats.
cd $seqdir1/D1_metabat_output
for fa in *.fa
do
bwa index $faa
bwa mem -t 6 $fa $source/RNA_trim_37.left_paired.trimmed.fastq.gz $source/RNA_trim_37.right_paired.trimmed.fastq.gz > $fa.sam  
samtools sort -@ 2 -o ${fa}_sort.bam $fa.sam
done


#D3
cd $seqdir1/D3_metabat_output
for faa in *.fa
do
bwa index $faa 
bwa mem -t 6 $faa $source/RNA_trim_39.left_paired.trimmed.fastq.gz $source/RNA_trim_39.right_paired.trimmed.fastq.gz > $faa.sam 
samtools sort -@ 2 -o ${faa}_sort.bam $faa.sam
done

