#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 08:00:00
#SBATCH -J BWA_for_DNA_metabat
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

# Load modules
module load bioinfo-tools
module load bwa
module load samtools

#directories used
seqdir1="/home/kvenk811/Genome_Analysis_1MB462/Results/Metabat_binning_before_bwa"
seqdir2="/proj/genomeanalysis2022/nobackup/work/kvenk811/metabat_after_bwa"
outdir="/proj/genomeanalysis2022/nobackup/work/kvenk811/bwa_conc_rna_map"
source="/home/kvenk811/Genome_Analysis_1MB462/Data/RNA_trimmed_files"


# Create a reference .fa file with db to align to that is a contcatenated file of all bins at a site
# from supplementary material
cd $outdir
for i in $seqdir1/D1_metabat_output/*.fa; do name=`echo $i | awk 'BEGIN{FS="."}{print $1$2}'`; echo ">"$name >> D1_allbins_concat.fa; grep -v '>' $i >> D1_allbins_concat.fa; done
mv D1_allbins_concat.fa D1_conc/

for j in $seqdir1/D1_metabat_output/*.fa; do name=`echo $j | awk 'BEGIN{FS="."}{print $2}'`; echo ">"$name >> D3_allbins_concat.fa; grep -v '>' $j >> D3_allbins_concat.fa; done
mv D3_allbins_concat.fa D3_conc/


# Align RNA reads to concatenated fasta file, and convert to a sorted bam format.
# Also produce some index stats.
bwa index D1_allbins_concat.fa 2>D1_index.out
bwa mem -t 2 D1_allbins_concat.fa $source/RNA_trim_D1_1.paired.trimmed.fastq.gz $source/RNA_trim_D1_2.paired.trimmed.fastq.gz > D1_supercontig.RNA.aln.sam 2>D1_bwamem.out
samtools view -@ 2 -bS  D1_supercontig.RNA.aln.sam | 
samtools sort -@ 2 -o D1_supercontig.RNA.aln.bam -
samtools index D1_supercontig.RNA.aln.bam
samtools idxstats D1_supercontig.RNA.aln.bam > D1_supercontig.RNA.aln.stats

#alt code
# For D1
#bwa index $seqdir/D1_megahit_output/final.contigs.fa
#bwa mem -t 10 D1_allbins_concat.fa $source/RNA_trim_D1_1.paired.trimmed.fastq.gz $source/RNA_trim_D1_2.paired.trimmed.fastq.gz 2> $OUTDIR/D1/D1_mem.out | samtools sort -o $OUTDIR/D1/D1_sorted.bam

#D3
bwa index D3_allbins_concat.fa 2>D3_index.out
bwa mem -t 2 D3_allbins_concat.fa $source/RNA_trim_D3_1.paired.trimmed.fastq.gz $source/RNA_trim_D3_2.paired.trimmed.fastq.gz > D3_supercontig.RNA.aln.sam 2>D3_bwamem.out
samtools view -@ 2 -bS  D3_supercontig.RNA.aln.sam | 
samtools sort -@ 2 -o D3_supercontig.RNA.aln.bam -
samtools index D3_supercontig.RNA.aln.bam
samtools idxstats D3_supercontig.RNA.aln.bam > D3_supercontig.RNA.aln.stats

#alt code
# For D1
#bwa index $seqdir/D1_megahit_output/final.contigs.fa
#bwa mem -t 10 D3_allbins_concat.fa $source/RNA_trim_D3_1.paired.trimmed.fastq.gz $source/RNA_trim_D3_2.paired.trimmed.fastq.gz 2> $OUTDIR/D3/D3_mem.out | samtools sort -o $OUTDIR/D3/D3_sorted.bam

