#!/bin/bash -l
#SBATCH -A uppmax2022-2-5 -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -J phylogenetic_phylophlan
#SBATCH -t 10:00:00
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

set -x

#script for phylogenetic reconstruction

#this script takes bins from binning without structural (Proka)/ functional (eggNOGmapper) annotation
#load the necessary modules
module load bioinfo-tools phylophlan/0.99
module unload python
module load python/2.7.15 biopython/1.73 FastTree muscle/3.8.31 usearch/5.2.32
seqdir="/proj/genomeanalysis2022/nobackup/work/kvenk811/prokka_before_bwa"
outdir="/proj/genomeanalysis2022/nobackup/work/kvenk811/phylophlan"



# The input .fa files will be the Prokka output, as these include amino acid sequence and not only nucleotide, in contrast to the binning output. 
# Further, the file names have to be given new names.
#cd $seqdir/D1
#for bins in *ann.out
#do
#echo $bins
#for files in $bins/*
#do
#echo $files
#mv "$files" "${files/PROKKA_05032022/$bins}"
#done
#done

#cd $seqdir/D3
#for bins in *ann.out
#do
#echo $bins
#for files in $bins/*
#do
#echo $files
#mv "$files" "${files/PROKKA_05032022/$bins}"
#done
#done

#not used but good to have
# did the copying of phylophlan stuff directly in the folder
# Symlink the phylophlan data files
#cd  $OUTDIR/
#mkdir data
#cd data
#mkdir -p ppaalns
#ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/*.bz2 .
#ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppaalns/*.bz2 ppaalns/
#ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/data/ppafull.tax.txt .
#ln -sf /sw/apps/bioinfo/phylophlan/0.99/rackham/bin/taxcuration/ $OUTDIR 

# Prokka output will be the input for phylophlan since it has DNA/AA-sequence for the genes in the bins/genome
#ln -s $seqdir/D1/*ann.out/*.faa $outdir/input/D1/
#ln -s $seqdir/D3/*ann.out/*.faa $outdir/input/D3/

#run phylophlan nproc -- number of CPUs -i input -o output with error file D1/D3_phylo.err
$outdir
phylophlan.py -i -t --nproc 2 D1
phylophlan.py -i -t --nproc 2 D3
