#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 00:30:00
#SBATCH -J trim_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

module load bioinfo-tools
module load FastQC/0.11.9

DATA = "/home/kvenk811/Genome_Analysis_1MB462/Data/raw_data/3_Thrash_2017"
OUT = "/home/kvenk811/Genome_Analysis_1MB462/Results/FASTQC"

#untrimmed RNA fastqc analysis
for file in $DATA/RNA_untrimmed/*
do
fastqc $file -o $OUT/RNA_untrimmed
done

#trimmed RNA fastqc analysis
for file in $DATA/RNA_trimmed/*
do
fastqc $file -o $OUT/RNA_trimmed
done

#trimmed DNA fastqc analysis
for file in $DATAB462/DNA_trimmed/*
do
fastqc $file -o $OUT/DNA_quality
done
