#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 02:00:00
#SBATCH -J trim_RNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

module load bioinfo-tools
module load FastQC/0.11.9

#untrimmed RNA fastqc analysis
for file in /home/kvenk811/Genome_Analysis_1MB462/Data/raw_data/3_Thrash_2017/RNA_untrimmed/*
do
fastqc $file -o /home/kvenk811/Genome_Analysis_1MB462/Data/fastqc/RNA_untrimmed/
done

#trimmed RNA fastqc analysis
for file in /home/kvenk811/Genome_Analysis_1MB462/Data/RNA_trimmed/*
do
fastqc $file -o /home/kvenk811/Genome_Analysis_1MB462/Data/fastqc/RNA_trimmed/
done

for file in /home/kvenk811/Genome_Analysis_1MB462/Data/raw_data/3_Thrash_2017/DNA_trimmed/*
do
fastqc $file -o /home/kvenk811/Genome_Analysis_1MB462/Data/fastqc/DNA_trimmed/
done
