#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 02:00:00
#SBATCH -J metaquast_analysis
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5398@student.uu.se

#Binning with MetaBat tool

#Load modules
module load bioinfo-tools
module load MetaBat

#Sequence directories
seq_in="/home/kvenk811/Genome_Analysis_1MB462/Results/Megahit_Assembly"
out="/home/kvenk811/Genome_Analysis_1MB462/Results/Megabat_binning"

metabat -i $seq_in/D1_megahit_output/final.contigs.fa -o $out/D1_metabat_output -t 2 -v
metabat -i $seq_in/D3_megahit_output/final.contigs.fa -o $out/D3_metabat_output -t 2 -v
