#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 15:00:00
#SBATCH -J BWA_for_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

# Load modules
module load bioinfo-tools
module load bwa
module load samtools

#directories
seqdir="/home/kvenk811/Genome_Analysis_1MB462/Results/Megahit_Assembly"
outdir="/home/kvenk811/Genome_Analysis_1MB462/Results/BWA_before_assembly"
rawdata="/home/kvenk811/Genome_Analysis_1MB462/Data/raw_data/3_Thrash_2017/DNA_trimmed"
# For D1
bwa index $seqdir/D1_assembly_output/final.contigs.fa
bwa mem -t 10 $seq/D1_assembly_output/final.contigs.fa $rawdata/SRR4342129_1.paired.trimmed.fastq.gz $rawdata/SRR4342129_2.paired.trimmed.fastq.gz 2> $outdir/D1_BWA/bwa_DNA_D1_sam.sam

# For D3
bwa index $seqdir/D3_assembly_output/final.contigs.fa
bwa mem -t 10 $seqdir/D3_assembly_output/final.contigs.fa $rawdata/SRR4342133_1.paired.trimmed.fastq.gz $rawdata/SRR4342133_2.paired.trimmed.fastq.gz 2> $outdir/D3_BWA/bwa_DNA_D3_sam.sam

# Convert sam to bam file
samtools view -S -b $outdir/D1_BWA/bwa_DNA_D1.sam > $outdir/D1_BWA/bwa_DNA_D1_bam.bam
samtools view -S -b $outdir/D3_BWA/bwa_DNA_D3.sam > $outdir/D3_BWA/bwa_DNA_D3_bam.bam


# Create depth file 
#jgi_summarize_bam_contig_depths --outputDepth /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/D1_depth.txt --pairedContigs /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/D1_paired.txt /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D1-SRR4342129_bwa/bwa_DNA_D1-SRR4342129.bam
#jgi_summarize_bam_contig_depths --outputDepth /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/D3_depth.txt --pairedContigs /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/D3_paired.txt /home/andreak/Genome_Analysis/Genome-Analysis/data/BWA_DNA/D3-SRR4342133_bwa/bwa_DNA_D3-SRR4342133.bam

#metabat -i assembly.fa -a depth.txt -p paired.txt -o bin3 --specific -l -v --saveTNF saved.tnf --saveDistance saved.gprob
