#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 2
#SBATCH -t 08:00:00
#SBATCH -J BWA_for_DNA
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

# Load modules
module load bioinfo-tools
module load bwa
module load samtools
module load MetaBat

#directories
seqdir="/home/kvenk811/Genome_Analysis_1MB462/Results/Megahit_Assembly"
outdir="/proj/genomeanalysis2022/nobackup/work/kvenk811/BWA_before_metabat"
rawdata="/home/kvenk811/Genome_Analysis_1MB462/Data/raw_data/3_Thrash_2017/DNA_trimmed"
outmet="/proj/genomeanalysis2022/nobackup/work/kvenk811/metabat_after_bwa"

# For D1
bwa index $seqdir/D1_megahit_output/final.contigs.fa
bwa mem -t 10 $seqdir/D1_megahit_output/final.contigs.fa $rawdata/SRR4342129_1.paired.trimmed.fastq.gz $rawdata/SRR4342129_2.paired.trimmed.fastq.gz 2> $outdir/D1_BWA/D1.bam.bwa.log | samtools sort -o $outdir/D1_BWA/D1.sorted.bam

# For D3
bwa index $seqdir/D3_megahit_output/final.contigs.fa
bwa mem -t 10 $seqdir/D3_megahit_output/final.contigs.fa $rawdata/SRR4342133_1.paired.trimmed.fastq.gz $rawdata/SRR4342133_2.paired.trimmed.fastq.gz 2> $outdir/D3_BWA/bwa_DNA_D3_sam.sam | samtools sort -o $outdir/D3_BWA/D3.sorted.bam

# Run MetaBat with depth.txt on D1 and D3
#jgi_summarize_bam_contig_depths --outputDepth $outdir/D1_BWA/depth.txt --pairedContigs $OUTDIR/D1/paired.txt $OUTDIR/D1/*.bam 
#metabat -i $CONTIGDIR/D1_megahit_output/final.contigs.fa -a $OUTDIR/D1/depth.txt -p $OUTDIR/D1/paired.txt --specific -v --saveTNF $OUTDIR/D1/saved.tnf --saveDistance $OUTDIR/D1/saved.gprob -o $OUTDIR/metabat_output/D1/D1_normalized

#jgi_summarize_bam_contig_depths --outputDepth $OUTDIR/D3/depth.txt --pairedContigs $OUTDIR/D3/paired.txt $OUTDIR/D3/*.bam
#metabat -i $CONTIGDIR/D3_megahit_output/final.contigs.fa -a $OUTDIR/D3/depth.txt -p $OUTDIR/D3/paired.txt --specific -v --saveTNF $OUTDIR/D3/saved.tnf --saveDistance $OUTDIR/D3/saved.gprob -o $OUTDIR/metabat_output/D3/D3_normalized
