#!/bin/bash -l
#SBATCH -A uppmax2022-2-5
#SBATCH -M snowy
#SBATCH -p core
#SBATCH -n 4
#SBATCH -t 01:00:00
#SBATCH -J Checkm_for_bwa
#SBATCH --mail-type=ALL
#SBATCH --mail-user kaavya.venkateswaran.5938@student.uu.se

set -x

#load modules
module load bioinfo-tools 
module load CheckM

#directories
seq="/proj/genomeanalysis2022/nobackup/work/kvenk811/metabat_after_bwa"
out="/proj/genomeanalysis2022/nobackup/work/kvenk811/Checkm_for_BWA_Metabat_DNA" #create this driectory
cd /proj/genomeanalysis2022/nobackup/work/kvenk811/

if ! [ -d $out/Checkm_for_BWA_Metabat_DNA ]
then
mkdir $out/Checkm_for_BWA_Metabat_DNA
fi

#see if directories exist, or create
if ! [ -d $out/D1_checkm ]
then
mkdir $out/D1_checkm
fi

if ! [ -d $out/D3_checkm ]
then
mkdir $out/D3_checkm
fi

# Download the CheckM data to current directory
cp -av $CHECKM_DATA/2015_01_16/* .

#set up the location of the database so CheckM can find it
checkm data setRoot $PWD

# Run the analyses with combined workflow: lineage_wf. Then follow up with analyze and qa to create ...
checkm lineage_wf -t 8 -x fa --reduced_tree $seq/D1_normalized/ $out/D1_checkm
checkm lineage_wf -t 8 -x fa --reduced_tree $seq/D3_normalized/ $out/D3_checkm

#for checkm marker genes in the bins
checkm analyze -t 8 -x fa $out/D1_checkm/lineage.ms $seq/D1_metabat_output/ $out/D1_checkm/
checkm analyze -t 8 -x fa $out/D3_checkm/lineage.ms $seq/D3_metabat_output/ $out/D3_checkm/

#Assess bins for contamination and completeness
checkm qa -t 8 -o 1 -f $out/D1_checkm/qa.out $out/D1_checkm/lineage.ms $out/D1_checkm/
checkm qa -t 8 -o 1 -f $out/D3_checkm/qa.out $out/D3_checkm/lineage.ms $out/D3_checkm/
